export const CURRENCIES = [
  { code: 'AED', name: 'United Arab Emirates dirham' },
  { code: 'ARS', name: 'Argentine peso' },
  { code: 'AUD', name: 'Australian dollar' },
  { code: 'BDT', name: 'Bangladeshi taka' },
  { code: 'BHD', name: 'Bahraini dinar' },
  { code: 'BRL', name: 'Brazilian real' },
  { code: 'CAD', name: 'Canadian dollar' },
  { code: 'CHF', name: 'Swiss franc' },
  { code: 'CLP', name: 'Chilean peso' },
  { code: 'CNY', name: 'Chinese yuan' },
  { code: 'COP', name: 'Colombian peso' },
  { code: 'CZK', name: 'Czech koruna' },
  { code: 'DKK', name: 'Danish krone' },
  { code: 'DZD', name: 'Algerian dinar' },
  { code: 'EGP', name: 'Egyptian pound' },
  { code: 'ETB', name: 'Ethiopian birr' },
  { code: 'EUR', name: 'Euro' },
  { code: 'GBP', name: 'British pound' },
  { code: 'GHS', name: 'Ghanaian cedi' },
  { code: 'HKD', name: 'Hong Kong dollar' },
  { code: 'HUF', name: 'Hungarian forint' },
  { code: 'IDR', name: 'Indonesian rupiah' },
  { code: 'ILS', name: 'Israeli new shekel' },
  { code: 'INR', name: 'Indian rupee' },
  { code: 'JPY', name: 'Japanese yen' },
  { code: 'KES', name: 'Kenyan shilling' },
  { code: 'KRW', name: 'South Korean won' },
  { code: 'KWD', name: 'Kuwaiti dinar' },
  { code: 'MAD', name: 'Moroccan dirham' },
  { code: 'MUR', name: 'Mauritian rupee' },
  { code: 'MXN', name: 'Mexican peso' },
  { code: 'MYR', name: 'Malaysian ringgit' },
  { code: 'NGN', name: 'Nigerian naira' },
  { code: 'NOK', name: 'Norwegian krone' },
  { code: 'NPR', name: 'Nepalese rupee' },
  { code: 'NZD', name: 'New Zealand dollar' },
  { code: 'OMR', name: 'Omani rial' },
  { code: 'PHP', name: 'Philippine peso' },
  { code: 'PKR', name: 'Pakistani rupee' },
  { code: 'PLN', name: 'Polish zloty' },
  { code: 'QAR', name: 'Qatari riyal' },
  { code: 'RON', name: 'Romanian leu' },
  { code: 'RUB', name: 'Russian ruble' },
  { code: 'SAR', name: 'Saudi riyal' },
  { code: 'SEK', name: 'Swedish krona' },
  { code: 'SGD', name: 'Singapore dollar' },
  { code: 'THB', name: 'Thai baht' },
  { code: 'TND', name: 'Tunisian dinar' },
  { code: 'TRY', name: 'Turkish lira' },
  { code: 'TZS', name: 'Tanzanian shilling' },
  { code: 'UGX', name: 'Ugandan shilling' },
  { code: 'USD', name: 'United States dollar' },
  { code: 'UYU', name: 'Uruguayan peso' },
  { code: 'VND', name: 'Vietnamese dong' },
  { code: 'XOF', name: 'West African CFA franc' },
  { code: 'ZAR', name: 'South African rand' },
  { code: 'ZMW', name: 'Zambian kwacha' },
]
